(function(){'use strict';
var CK='legendaryai_conversations_v2',AK='legendaryai_active_conv_v2',DK='legendaryai_draft_v1';
var input=document.getElementById('chatInput'),form=document.getElementById('chatForm'),app=document.getElementById('chatApp'),list=document.getElementById('convList');
if(!app)return;
function conv(){try{var a=JSON.parse(localStorage.getItem(CK)||'[]'),id=localStorage.getItem(AK);return a.find(function(x){return x.id===id})||a[0]||null}catch(e){return null}}
function slug(s){return String(s||'legendary-chat').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70)||'legendary-chat'}
function toast(t){var n=document.getElementById('laPowerToast');if(!n){n=document.createElement('div');n.id='laPowerToast';document.body.appendChild(n)}n.textContent=t;n.classList.add('show');clearTimeout(n._t);n._t=setTimeout(function(){n.classList.remove('show')},2200)}
function download(name,text,type){var u=URL.createObjectURL(new Blob([text],{type:type||'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(u)},1000)}
function exportChat(kind){var c=conv();if(!c)return toast('Chưa có hội thoại để xuất');if(kind==='json'){download(slug(c.title)+'.json',JSON.stringify(c,null,2),'application/json;charset=utf-8');return toast('✓ Đã xuất JSON')}var out=['# '+c.title,'','Xuất từ Legendary AI',''];(c.messages||[]).forEach(function(m){out.push(m.role==='user'?'## Bạn':'## Legendary AI',m.text||'','')});download(slug(c.title)+'.md',out.join('\n'),'text/markdown;charset=utf-8');toast('✓ Đã xuất Markdown')}
function copyChat(){var c=conv();if(!c)return;var t=(c.messages||[]).map(function(m){return(m.role==='user'?'Bạn':'Legendary AI')+':\n'+(m.text||'')}).join('\n\n');if(navigator.clipboard)navigator.clipboard.writeText(t).then(function(){toast('✓ Đã sao chép toàn bộ hội thoại')})}
function setInput(v){if(!input)return;input.value=v;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus()}
var prompts=[
['Coder','Bạn là kỹ sư phần mềm senior. Ưu tiên giải pháp production-ready, an toàn, dễ test và nêu trade-off quan trọng.'],
['Debug','Debug theo thứ tự: triệu chứng → nguyên nhân → cách kiểm tra → bản sửa hoàn chỉnh → test hồi quy.'],
['Research','Tách dữ kiện, giả định và điều chưa chắc chắn. Trình bày kết luận → bằng chứng → giới hạn → bước tiếp theo.'],
['Writer','Biên tập nội dung tự nhiên, rõ ràng, đúng đối tượng; giữ nguyên ý định và tránh sáo rỗng.'],
['Product','Phân tích yêu cầu, edge cases, UX, dữ liệu, bảo mật và implementation theo từng bước.'],
['Teacher','Giải thích từ trực giác → ví dụ → nguyên lý → bài tập kiểm tra; không bỏ qua phần khó.'],
['Concise','Trả lời ngắn gọn, trực tiếp; ưu tiên checklist hoặc các bước hành động.'],
['Review','Review như reviewer khó tính: tìm lỗi, rủi ro, điểm chưa rõ và đề xuất bản sửa cụ thể.']
];
function overlay(id,title){var old=document.getElementById(id);if(old)old.remove();var b=document.createElement('div');b.id=id;b.className='la-overlay';var p=document.createElement('div');p.className='la-panel';var h=document.createElement('div');h.className='la-panel-head';var t=document.createElement('h3');t.textContent=title;var x=document.createElement('button');x.className='la-close';x.type='button';x.textContent='×';h.append(t,x);p.appendChild(h);b.appendChild(p);document.body.appendChild(b);function close(){b.remove()}x.onclick=close;b.onclick=function(e){if(e.target===b)close()};return{b:b,p:p,close:close}}
function promptsUI(){var u=overlay('laPrompts','Prompt Library'),g=document.createElement('div');g.className='la-prompt-grid';prompts.forEach(function(q){var b=document.createElement('button');b.className='la-prompt-card';b.type='button';var s=document.createElement('strong');s.textContent=q[0],d=document.createElement('span');d.textContent=q[1];b.append(s,d);b.onclick=function(){setInput(q[1]+'\n\n');u.close()};g.appendChild(b)});u.p.appendChild(g);u.b.classList.add('open')}
function diagnostics(){var u=overlay('laDiag','System diagnostics'),g=document.createElement('div');g.className='la-diagnostics';[['Engine JS',!!window.LegendaryAIEngine,'Legendary Engine đã tải'],['Supabase config',!!(window.LEGENDARY_SUPABASE_CONFIG&&window.LEGENDARY_SUPABASE_CONFIG.url),'Endpoint đã cấu hình'],['Backend client',!!window.LegendaryBackend,'Backend client đã khởi tạo'],['Local storage',!!window.localStorage,'Lưu hội thoại cục bộ khả dụng'],['Network',navigator.onLine,navigator.onLine?'Online':'Offline']].forEach(function(x){var r=document.createElement('div');r.className='la-diag-row';var st=x[1]?'✓':'!';r.innerHTML='<b>'+x[0]+'</b><strong class="'+(x[1]?'ok':'bad')+'">'+st+'</strong><small>'+x[2]+'</small>';g.appendChild(r)});u.p.appendChild(g);u.b.classList.add('open')}
function commands(){var u=overlay('laCmd','Quick actions'),s=document.createElement('input');s.className='la-command-search';s.placeholder='Tìm hành động…';u.p.appendChild(s);var g=document.createElement('div');g.className='la-command-list';u.p.appendChild(g);var a=[
['Trò chuyện mới','Ctrl/⌘ Shift N',function(){document.getElementById('newChatBtn')?.click();u.close()}],
['Tập trung ô nhập','Ctrl/⌘ /',function(){input?.focus();u.close()}],
['Prompt Library','',function(){u.close();promptsUI()}],
['Sao chép hội thoại','',function(){copyChat();u.close()}],
['Xuất Markdown','',function(){exportChat('md');u.close()}],
['Xuất JSON','',function(){exportChat('json');u.close()}],
['Chẩn đoán hệ thống','',function(){u.close();diagnostics()}],
['Toàn màn hình','',function(){document.getElementById('expandChatBtn')?.click();u.close()}]
];function render(q){g.innerHTML='';q=(q||'').toLowerCase();a.filter(function(x){return !q||x[0].toLowerCase().includes(q)}).forEach(function(x){var b=document.createElement('button');b.className='la-command';b.type='button';b.innerHTML='<span>'+x[0]+'</span><kbd>'+x[1]+'</kbd>';b.onclick=x[2];g.appendChild(b)})}s.oninput=function(){render(s.value)};render('');u.b.classList.add('open');s.focus()}
function searchBox(){if(!list||document.getElementById('laSearch'))return;var s=document.createElement('input');s.id='laSearch';s.type='search';s.placeholder='⌕ Tìm hội thoại…';s.setAttribute('aria-label','Tìm hội thoại');list.parentNode.insertBefore(s,list);function f(){var q=s.value.toLowerCase().trim();Array.prototype.forEach.call(list.children,function(x){var t=(x.querySelector('.conv-title')||{}).textContent||'';x.hidden=!!q&&!t.toLowerCase().includes(q)})}s.oninput=f;new MutationObserver(f).observe(list,{childList:true})}
function toolbar(){var r=app.querySelector('.chat-topbar-right');if(!r||document.getElementById('laTools'))return;var w=document.createElement('div');w.id='laTools';[['copy','⧉','Sao chép'],['md','↓','Xuất Markdown'],['json','{}','Xuất JSON']].forEach(function(x){var b=document.createElement('button');b.type='button';b.className='la-power-btn';b.textContent=x[1];b.title=x[2];b.dataset.a=x[0];w.appendChild(b)});r.insertBefore(w,r.firstChild);w.onclick=function(e){var b=e.target.closest('.la-power-btn');if(!b)return;if(b.dataset.a==='copy')copyChat();else exportChat(b.dataset.a==='json'?'json':'md')}}
function promptButton(){var s=document.getElementById('chatSuggestions');if(!s||document.getElementById('laPrompt'))return;var b=document.createElement('button');b.type='button';b.id='laPrompt';b.textContent='✦ Prompt Library';s.appendChild(b);b.onclick=promptsUI}
function draft(){if(!input)return;try{var d=localStorage.getItem(DK);if(d&&!input.value)input.value=d}catch(e){}var tm;input.addEventListener('input',function(){clearTimeout(tm);tm=setTimeout(function(){try{if(input.value)localStorage.setItem(DK,input.value);else localStorage.removeItem(DK)}catch(e){}},180)});if(form)form.addEventListener('submit',function(){try{localStorage.removeItem(DK)}catch(e){}},true)}
function stats(){var c=document.getElementById('chatCharCount');if(!input||!c)return;input.addEventListener('input',function(){var n=input.value.length;c.textContent=n.toLocaleString('vi-VN')+' ký tự · ~'+Math.ceil(n/4).toLocaleString('vi-VN')+' token'})}
function diagButton(){var s=document.getElementById('settingsBtn');if(!s||document.getElementById('laDiagBtn'))return;var b=document.createElement('button');b.id='laDiagBtn';b.type='button';b.className='btn btn-ghost btn-sm';b.textContent='⌁';b.title='Chẩn đoán hệ thống';s.parentNode.insertBefore(b,s);b.onclick=diagnostics}
function keys(){document.addEventListener('keydown',function(e){var m=e.ctrlKey||e.metaKey;if(m&&e.key.toLowerCase()==='k'){e.preventDefault();commands()}else if(m&&e.shiftKey&&e.key.toLowerCase()==='n'){e.preventDefault();document.getElementById('newChatBtn')?.click()}else if(m&&e.key==='/'){e.preventDefault();input?.focus()}else if(e.key==='Escape'){['laCmd','laPrompts','laDiag'].forEach(function(id){var x=document.getElementById(id);if(x)x.remove()})}})}
function boot(){toolbar();searchBox();promptButton();draft();stats();diagButton();keys()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.LegendaryPowerSuite={commands:commands,prompts:promptsUI,diagnostics:diagnostics,exportChat:exportChat};
})();